#!/bin/bash

echo "Installing DisWeb..."
mkdir -p $HOME/.local/share
mkdir -p $HOME/.local/share/applications
cd $HOME
wget https://oxmc.github.io/diswebreleaseserver/latest/full/Discord-armv7l/DisWeb.zip
sudo apt install -y unzip libnotify-bin
sudo unzip $HOME/DisWeb.zip -d $HOME/.local/share
echo "[Desktop Entry]
Name=DisWeb
Exec=$HOME/.local/share/DisWeb-linux-armv7l/DisWeb
Icon=$HOME/.local/share/DisWeb-linux-armv7l/resources/app/src/icons/app.png
Terminal=false
GenericName=Internet Messenger
Type=Application
StartupNotify=true
Categories=Network;InstantMessaging;Utility;
Encoding=UTF-8" > $HOME/.local/share/applications/DisWeb.desktop
echo "DisWeb has been installed successfully!"
cd $HOME
rm -rf $HOME/DisWeb.zip
echo "You can find DisWeb in Menu > Accessories > DisWeb."
