#!/bin/bash

echo "Installing Discord..."
cd $HOME
wget https://github.com/oxmc/disweb/releases/download/Test/Discord.zip
sudo apt install -y unzip
sudo unzip $HOME/Discord.zip -d $HOME/.local/share
echo "[Desktop Entry]
Name=Discord for raspberry pi's
Exec=/usr/share/Discord/Discord-webapp
Icon=/usr/share/Discord/resources/app/src/icons/app.png
Terminal=false
GenericName=Internet Messenger
Type=Application
StartupNotify=true
Categories=Network;InstantMessaging;Utility;
Encoding=UTF-8" > $HOME/.local/share/applications/Discord.desktop
echo "Discord is now installed!"
cd $HOME
rm -rf $HOME/Discord.zip
echo "You can find Discord in Menu > Accessories > Discord for raspbery pi's."
